version: '3.9'
name: picky-images-app
services:
  web:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./sqlite.db
      - S3_ENDPOINT=minio
      - S3_PORT=9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=miniosecret
      - S3_BUCKET_NAME=imagesbucket
      - S3_USE_SSL=false
    depends_on:
      - minio
    command: sh setup.sh

  minio:
    container_name: minio_storage
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      while ! /usr/bin/mc alias set myminio http://minio:9000 minio miniosecret; do
        echo 'MinIO is not ready yet, retrying in 2 seconds...';
        sleep 2;
      done;
      echo 'MinIO is ready! Proceeding with bucket setup.';
      /usr/bin/mc mb myminio/imagesbucket || true;
      /usr/bin/mc anonymous set public myminio/imagesbucket;
      exit 0;
      "
volumes:
  minio_storage:
